site_name: OpenPecha
repo_name: OpenPecha/Toolkit
repo_url: https://github.com/OpenPecha/Toolkit
edit_uri: "blob/master/docs/docs"

theme:
  name: material
  palette:
    - scheme: default
      primary: 
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  logo: logo.png
  features:
    - search.highlight
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - navigation.expand

nav:
  - Home: index.md
  - Pecha Data:
    - Featured datasets: data/featured-datasets.md
    - Reference: data/reference.md
    - GitHub: data/github.md
    - Core concepts: data/core-concepts.md
  - Pecha Tools:
    - Pecha Tools overview: tools/overview.md
  - Pecha API:
    - Getting started: api/getting-started.md
    - Reference: api/reference.md
  - Python library:
    - Overview: toolkit/toolkit-overview.md  
    - Installation: toolkit/install.md
    - Aquisition pipeline: toolkit/acquisition-pipeline.md
    - E-text operations: toolkit/etext-operations.md
    - Publishing pipeline: toolkit/publishing-pipeline.md
  - Benchmarks: benchmarks.md
  - Blog: 
    - OpenPecha blog: blog/index.md
  - Community:
    - Partners: community/partners.md
    - Stay informed: community/stay-informed.md
    - Connect: community/connect.md
    
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search
  - mkdocstrings
  - blog
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenPecha
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/7GFpPFSTeA
    - icon: fontawesome/brands/medium
      link: https://medium.com/@OpenPecha
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openpecha
      
extra_css:
  - stylesheets/extra.css  
